import { Request, Response, NextFunction } from 'express';
import { fetchTopMarkets } from '../services/polymarket.service';
import { analyzeMarketsBatch, groqCallLLM, groqExecutionCallLLM, SignalOutput } from '../services/ai.service';
import { runStrategyAgent } from '../strategy-agent';
import { runExecutionAgent, WDKContext } from '../execution-agent';
import { getWallet } from '../utils/wallet';
import logger from '../utils/logger';

export const getSignals = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const limit = req.query.limit ? parseInt(req.query.limit as string, 10) : 50;
    const markets = await fetchTopMarkets(limit);

    const BATCH_SIZE = 5;
    const allSignals: SignalOutput[] = [];

    // Process in batches
    for (let i = 0; i < markets.length; i += BATCH_SIZE) {
      const batch = markets.slice(i, i + BATCH_SIZE);
      logger.info(`Processing batch ${i / BATCH_SIZE + 1} of ${Math.ceil(markets.length / BATCH_SIZE)}...`);

      const batchSignals = await analyzeMarketsBatch(batch);

      // Filter only relevant signals
      const relevantSignals = batchSignals.filter(signal => signal.is_relevant);
      allSignals.push(...relevantSignals);
    }

    logger.info(`Running Strategy Agent on ${allSignals.length} relevant signals...`);
    const strategy = await runStrategyAgent(allSignals, groqCallLLM);

    logger.info('Running Execution Agent on the strategy decision...');

    // We optionally use the authenticated user's seed phrase, or fall back to a dummy one
    // generated by getWallet() if this endpoint is called without auth.
    const userSeedPhrase = (req as any).user?.seedPhrase;
    const { account } = await getWallet(userSeedPhrase);

    const ctx: WDKContext = {
      evmAccount: account,
      // Total portfolio value in USD — pctToUsdt() converts this to raw USDT base units
      // (i.e. 1000 here means $1000 portfolio; 15% → 150 USDT → 150_000_000n)
      totalPortfolioUSDT: 1000,
      swapMaxFee: undefined,
    };

    const execution = await runExecutionAgent(strategy, ctx, groqExecutionCallLLM);

    res.status(200).json({
      status: 'success',
      count: allSignals.length,
      data: allSignals,
      strategy,
      execution,
    });
  } catch (error) {
    next(error);
  }
};
